# Import the dataset 
First we will import a female-only dataset consisting in close to 3000 hotel reviews.

In [191]:
#read the file
import csv

datasetClass = []
datasetData = []

with open('male-only.csv', 'r', encoding='utf-8') as csvFile:
    reader = csv.reader(csvFile,delimiter = ';')
    for row in reader:
        datasetClass.append( row[0].strip() )
        datasetData.append( row[1].strip() )
        
csvFile.close()

print("Result: ")
print (str(len(datasetClass)) + " comments have been imported" )

Result: 
2997 comments have been imported


In [192]:
#divide the training dataset to evaluate it
cont = 0
trainingData = []
trainingClass = []

testData = []
testClass = []

for index in range(len(datasetClass)):
    if cont % 10 == 0:
        testData.append(datasetData[index])
        testClass.append(datasetClass[index])
    else:
        trainingData.append(datasetData[index])
        trainingClass.append(datasetClass[index])
    cont = cont + 1    

In [193]:
#train the classifier model
from sklearn.linear_model import SGDClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline

text_clf = Pipeline([
     ('vect', CountVectorizer(stop_words='english',ngram_range=(1, 3))),
     ('tfidf', TfidfTransformer()),
     ('clf', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, random_state=42,max_iter=5, tol=None)),
])

text_clf.fit(trainingData,trainingClass)

Pipeline(memory=None,
         steps=[('vect',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 3), preprocessor=None,
                                 stop_words='english', strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabular...
                ('clf',
                 SGDClassifier(alpha=0.001, average=False, class_weight=None,
                               early_stopping=False, epsilon=0.1, eta0=0.0,
                               fit_intercept=True, l1_ratio=0.15,
                               learning_rate='optimal', loss='hinge',
                      

In [194]:
#test the model
import numpy as np
from sklearn import metrics

predicted = text_clf.predict(testData)


print("--------------------------------------------------------------------------------")
print("CASE: ")
print("--------------------------------------------------------------------------------")
print("")

print("Accuracy: " + str(np.mean(predicted == testClass)))

print("")
print("")
print("CONFUSION MATRIX")
print("")
print(metrics.confusion_matrix(testClass, predicted))




--------------------------------------------------------------------------------
CASE: 
--------------------------------------------------------------------------------

Accuracy: 0.7233333333333334


CONFUSION MATRIX

[[91  6  3]
 [30 29 41]
 [ 3  0 97]]


In [195]:
#now lets try to predict male comments using our female-only trained model
maleOnlydatasetClass = []
maleOnlydatasetData = []

with open('female-only.csv', 'r', encoding='utf-8') as csvFile:
    reader = csv.reader(csvFile,delimiter = ';')
    for row in reader:
        maleOnlydatasetClass.append( row[0].strip() )
        maleOnlydatasetData.append( row[1].strip() )
        
csvFile.close()


testData = []
testClass = []

for index in range(len(datasetClass)):
    if cont % 10 == 0:
        testData.append(maleOnlydatasetData[index])
        testClass.append(maleOnlydatasetClass[index])
    cont = cont + 1   
    

predicted = text_clf.predict(testData)


print("--------------------------------------------------------------------------------")
print("CASE: ")
print("--------------------------------------------------------------------------------")
print("")
print("Accuracy: " + str(np.mean(predicted == testClass)))
print("")
print("")

print("CONFUSION MATRIX")
print("")

print(metrics.confusion_matrix(testClass, predicted))

print("")
print("")



--------------------------------------------------------------------------------
CASE: 
--------------------------------------------------------------------------------

Accuracy: 0.98


CONFUSION MATRIX

[[100   0   0]
 [  4  94   2]
 [  0   0 100]]


